name: Build and Publish docs

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions: 
  contents: write

jobs:
  generatedocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.15
        
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build:docs

      - name: Publish to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: docs
